### ISSUE TITLE
Engine interface methods

### ISSUE THREAD

**Issue by YuriNeverov** [YuriNeverov/ChessGame#2]
We need to provide such methods as
```
Color getCellColor(Cell cell);
ChessPiece getChessPiece(Cell cell);
boolean isValidMove(Move move);
boolean makeMove(Move move);
Set<Move> getValidMovesFrom(Cell cell);
boolean isCheck(Color color);
boolean isCheckmate(Color color);
```

**Comment by RoyalTunez** [comment]
зачем тебе 2 метода для проверки корректности хода и его делания?
Зачем тебе Set в getValidMoves?
И непонятно зачем тебе цвет в шахе.

**Comment by YuriNeverov** [comment]
> зачем тебе 2 метода для проверки корректности хода и его делания?

There is different logic in these methods. One is read-only, while other is for update.

**Comment by YuriNeverov** [comment]
Also, `Set<Cell>` is fine for me (and I suppose, for web) within `getValidMovesFrom()` method, as return value's type.

**Comment by RoyalTunez** [comment]
> Also, `Set<Cell>` is fine for me (and I suppose, for web) within `getValidMovesFrom()` method, as return value's type.

А List<Move> тебя устроит?

**Comment by YuriNeverov** [comment]
Also, `Color isCheckmate()` and `Color isCheck()` fine, if there will be some `NONE` value for `CheckPieces` enum.

**Comment by YuriNeverov** [comment]
> > Also, `Set<Cell>` is fine for me (and I suppose, for web) within `getValidMovesFrom()` method, as return value's type.
> 
> А List тебя устроит?

Why do we need order on cells?

**Comment by RoyalTunez** [comment]
> > > Also, `Set<Cell>` is fine for me (and I suppose, for web) within `getValidMovesFrom()` method, as return value's type.
> > 
> > 
> > А List тебя устроит?
> 
> Why do we need order on cells?

Слыш ты, по русски отвечай, ты чо пендос?
Так вроде в листе и нет упорядоченности, а в set есть.

**Comment by YuriNeverov** [comment]
> > > > Also, `Set<Cell>` is fine for me (and I suppose, for web) within `getValidMovesFrom()` method, as return value's type.
> > > 
> > > 
> > > А List тебя устроит?
> > 
> > 
> > Why do we need order on cells?
> 
> Слыш ты, по русски отвечай, ты чо пендос? Так вроде в листе и нет упорядоченности, а в set есть.

Please, check https://docs.oracle.com/javase/8/docs/api/java/util/List.html for info about `List`. It is an ordered collection by definition, while such collections as `HashSet` do not have order.

**Comment by YuriNeverov** [comment]
But you are still free to use `List<Cell>`

**Comment by RoyalTunez** [comment]
> But you are still free to use `List<Cell>`

Yes, my lord.
