### ISSUE TITLE
Move engine to separate gradle project

### ISSUE THREAD

**Issue by YuriNeverov** [YuriNeverov/ChessGame#3]
To import engine into every of our sub-projects (AI, Web and Android applications), we need to move engine to separate sub-project. 
I. e., we need such structure:
```
ChessGame/ai
ChessGame/engine
ChessGame/web
ChessGame/android
```
Also, to be able to import it into gradle projects, it should be gradle as well. You can achieve it by creating new project via IntelliJ IDEA choosing `ChessGame/engine` folder as a folder for new project.

![image](https://user-images.githubusercontent.com/47862299/146646756-f83ed164-c512-4ea1-a736-ebc525fa5c96.png)

Please, maintain such structure:
```
ChessGame/engine/gradle/
ChessGame/engine/src/main/java/engine/Board.java
ChessGame/engine/src/main/java/engine/Cell.java
ChessGame/engine/src/main/java/engine/ChessPiece.java
ChessGame/engine/src/main/java/engine/MatrixBoard.java
ChessGame/engine/src/main/java/engine/Move.java
ChessGame/engine/src/main/java/engine/Player.java
ChessGame/engine/src/main/java/engine/RandomPlayer.java
ChessGame/engine/build.gradle
ChessGame/engine/settings.gradle
```

**Comment by RoyalTunez** [comment]
Вечно пендосам что-то не нравится...
